# Kafka Config
kafka.bootstrap=localhost:9092
kafka.group.id=policy-group
kafka.topic.in=policy-in
kafka.topic.out=policy-out
kafka.enable.auto.commit=false
kafka.auto.offset.reset=earliest
kafka.consumer.threads=4
kafka.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Cache
cache.ttl.minutes=10
cache.max.size=1000
